# Generated by Django 2.2.24 on 2022-01-26 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='image',
        ),
    ]
