# Generated by Django 3.2.9 on 2022-01-26 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='Storecentre',
        ),
    ]
