# Generated by Django 2.2.24 on 2022-01-26 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_client_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='image',
        ),
    ]
