# Generated by Django 3.2.9 on 2022-01-26 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
