# Generated by Django 2.2.24 on 2022-01-25 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('type', models.CharField(choices=[('CLT', 'Client'), ('STF', 'Staff')], max_length=16)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Profile')),
            ],
        ),
    ]
