# Generated by Django 2.2.24 on 2022-01-25 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
