<<<<<<< HEAD
# Generated by Django 2.2.24 on 2022-01-26 10:26
=======

# Generated by Django 3.2.9 on 2022-01-26 06:39

>>>>>>> 3f895b5329b456a55c28ae0a28276f538e44f45d

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=20)),
                ('payment_method', models.CharField(max_length=50)),
                ('shipping_cost', models.CharField(max_length=50)),
            ],
        ),
    ]
