<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 3.2.9 on 2022-02-01 10:04
=======
# Generated by Django 3.2.9 on 2022-01-29 19:03
>>>>>>> 0dfa50aa701df5dfd0d65d9cac245e1a5dc39d41
=======
# Generated by Django 3.2.9 on 2022-02-01 10:12
>>>>>>> 2b81c9e80091ad14a356e8e7ab62d6a8e54e6f89

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=20)),
                ('payment_method', models.CharField(max_length=50)),
                ('shipping_cost', models.CharField(max_length=50)),
            ],
        ),
    ]
