# Generated by Django 3.2.9 on 2022-01-25 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('charge', models.IntegerField()),
                ('no_units', models.IntegerField(default=0)),
                ('available_units', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='goods',
            name='unit_no',
        ),
        migrations.AddField(
            model_name='goods',
            name='no_of_units',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
        migrations.AlterField(
            model_name='goods',
            name='storage_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='units.storage'),
        ),
    ]
