# Generated by Django 2.2.24 on 2022-01-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='srorage_type',
            new_name='storage_type',
        ),
    ]
