# Generated by Django 3.2.9 on 2022-01-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_auto_20220120_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='arrival_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='goods',
            name='departure_date',
            field=models.DateField(),
        ),
    ]
