# Generated by Django 2.2.24 on 2022-01-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_auto_20220126_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='tatol_cost',
            field=models.IntegerField(null=True),
        ),
    ]
