# Generated by Django 2.2.24 on 2022-01-21 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_auto_20220121_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='goods',
        ),
        migrations.AddField(
            model_name='goods',
            name='unit_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to='units.Unit'),
        ),
    ]
