# Generated by Django 2.2.24 on 2022-01-26 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_goods_tatol_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='tatol_cost',
            new_name='total_cost',
        ),
    ]
