# Generated by Django 3.2.9 on 2022-01-29 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='phone_number',
            field=models.CharField(help_text='Formart +254712345678', max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Input your Phone Number '),
        ),
    ]
