# Generated by Django 2.2.24 on 2022-01-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='goods',
        ),
        migrations.AddField(
            model_name='transport',
            name='transport_goods',
            field=models.ManyToManyField(to='units.Goods'),
        ),
    ]
