# Generated by Django 3.2.9 on 2022-01-24 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='county',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='town',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='transport_goods',
        ),
    ]
