# Generated by Django 3.2.9 on 2022-01-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_alter_transport_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='transport_type',
            field=models.CharField(choices=[('Pick-Up', 'Pick-Up'), ('Delivery', 'Delivery')], max_length=50),
        ),
    ]
