# Generated by Django 2.2.24 on 2022-01-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_auto_20220125_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
