# Generated by Django 2.2.24 on 2022-01-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_auto_20220120_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
