# Generated by Django 3.2.9 on 2022-01-31 06:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_alter_transport_transport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='phone_number',
            field=models.CharField(help_text='Formart 0712345678', max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Input your Phone Number '),
        ),
    ]
