# Generated by Django 2.2.24 on 2022-01-26 07:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_auto_20220125_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
