# Generated by Django 2.2.24 on 2022-01-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_auto_20220124_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
