# Generated by Django 3.2.9 on 2022-01-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_alter_transport_transport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='transport_type',
            field=models.CharField(choices=[('Pick-Up', 'Pick-Up'), ('Delivery', 'Delivery')], default='Pick-Up', max_length=50),
        ),
    ]
