# Generated by Django 2.2.24 on 2022-01-24 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_auto_20220124_1632'),
        ('transport', '0005_transport_is_approved'),
    ]

    operations = [
    ]
